path:
  data: $HOME/.cyclops/data
redis:
  # TCP Redis: tcp://host:post/dbNum
  address: tcp://localhost:6379/0
workers:
  - ALPHA
  - BETA
  - GAMMA
  - DELTA
  - EPSILON
  - ZETA
  - ETA
rest:
  host: 127.0.0.1
  port: 9090
settings:
  autosave: # Check the tree at given periods and saves it to disk if it's dirty.
    enabled: True
    interval: 10 # in seconds